version: "3"

volumes:
  postgres_data:

services:
  #db
  postgres:
    hostname: postgres
    image: postgres
    environment:
      - POSTGRES_HOST=
      - POSTGRES_PORT=5432
      - POSTGRES_ROOT_HOST=%
      - POSTGRES_DATABASE=chat_db
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev_password   # set a non-empty value for the POSTGRES_PASSWORD variable
      - POSTGRES_ROOT_PASSWORD=MysqlPassword@10
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres

  engine:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    command:
      bash -c "python manage.py migrate &&
      python manage.py runserver 0:8080"
    environment:
      - DB_HOST=postgres
      - DB_NAME=chat_db
      - DB_USER=dev
      - DB_PASS=dev
    depends_on:
      - postgres
    expose:
      - 8080

  # message broker
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6389"
