version: "3"

volumes:
  postgres_data:

services:
  engine1:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    command:
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8080:8080"

  engine2:
    build:
      context: .
    ports:
      - "8081:8080"
    volumes:
      - ./app:/app
    command:
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8080"
    ports:
      - "8081:8080"

  # message broker
  redis:
    restart: always
    image: redis:latest
    expose:
      - "6389"

  #nginx
  proxy:
    build: ./proxy
    ports:
      - 80:80
    depends_on: 
      - engine1
      - engine2
      - redis
